### PR TITLE
Added state property, play/pause actions and OAuth authorization handling

### PR DESCRIPTION
**Pull request by ppacher**
Hi,

This PR adds a new state property (OnOffProperty) and the OnOffSwitch type that allows to toggle between pause and play (dedicated actions are also available). Moreover, I added support for the Authorization Code flow since a access tokens generated via the developer console expire after an hour. Although the authentication process is a bit more complicated it will result in an access and refresh token that allows the spotify-adapter to stay authorized. The PR itself is still work-in-progress but any feedback from you would be great!

Thanks

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Nice!
I already thought about using the Authorization Code Flow but was not sure how to implement it in a practical way.
Neat trick with the callback page btw :grin:.

**Comment by beothy** [comment]
Hi!

Is there any chance that this PR will merged and released soon? I've just found Webthings Gateway and this adapter, and displaying current song and play/pause buttons would be real nice.

Thanks

**Comment by tim-hellhake** [comment]
Hi @beothy,

as I understood it the PR is not finished yet.
If you are interested in the play/pause buttons I could add that soon.

**Comment by ppacher** [comment]
Hi, as far as I remember the PR was mostly finished but I didn't had time to play around with webthings gateway lately. I'll rebase it to the latest master in the afternoon so it can either be merged as it is or updated to match the expectations. I'll try to help / finish as much as possible but I don't have a running webthings gateway right now

**Comment by tim-hellhake** [comment]
Hi @ppacher, nice to hear from you :)

> I'll try to help / finish as much as possible but I don't have a running webthings gateway right now

That's fine.
Just give me your go when you are finished and the build is green and I'll handle the rest.
I can test it on my gateway and add it in case something is missing.

**Comment by ppacher** [comment]
I rebased the PR to the latest master. @tim-hellhake thanks for that offer! I just went through it and IMHO this PR is as finished as I meant it to be :). Would be great if you could test if it still works. Though, getting a new webthings gateway up and running is definitely now on my top-list :)

**Comment by beothy** [comment]
@ppacher I would happily test it, but I don't know how to do that. How can I add it to my gateway locally?

**Comment by tim-hellhake** [comment]
@ppacher
> thanks for that offer!

You are welcome :)

@beothy
I'll merge this now and if everything works out well you can install it on your gateway soon!

**Comment by tim-hellhake** [comment]
@ppacher
There was a problem with the refresh token, but apart from this, it seems to work fine.
Nice work!

**Comment by tim-hellhake** [comment]
@beothy
As soon as the PR is merged you can install it on your gateway :)

**Pull request merged**
